### ISSUE TITLE
Create release for submission

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/gata#15]
@LinguList The journal asked us to provide the data in one of their featured repositories. The most reasonable options would be Zenodo and OSF. As many other CLDF datasets are also linked to Zenodo, I guess that this would be the most reasonable way. Does anything speak against creating a release 0.1 with the current form of the dataset? We would like to not delay the submission any further, and while there are some open issues (#13 for some utility plots, #10 codes that could be added for a Version 1.0, and #5 which is too much work to implement it right now for little reward), we think that they should not prevent us from creating this release for submission.

If you are okay with that, I would go ahead and create a release 0.1 and link it to a Zenodo page. Alternatively, we would put everything on an OSF repository for the submission process.

**Comment by LinguList** [comment]
I'd release it, yes.
