### ISSUE TITLE
Handling References: parse sources

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/gata#5]
In the spreadsheet in [raw/pooled_all.csv](https://github.com/MuffinLinwist/GATA/blob/main/raw/pooled_all.csv), you list sources in a colloquial style, not as their bibtex keys. They should be parsed in such a way that we have:

```
BibtexKey[pagerange]
```

So something like:

```
Muller (1963:555)
```

should be converted to:

```
Muller1963[555]
```

But note that this requires that the bibtex-keys are `AuthorYear`.

**Comment by CMUgarte** [comment]
The spreadsheet of data is the one named gata_raw.csv. Sources are in the format you specified.

**Comment by LinguList** [comment]
Okay, we miss the page number in `[]` brackets now. Can we add this there?

**Comment by FredericBlum** [comment]
I have added the pages as indicated. The script that converts the previous column can be found [here](https://github.com/cldf-datasets/gata/blob/main/raw/scripts/clean_years.py). @MuffinLinwist Feel free to check the script to see how I proceeded.
