### ISSUE TITLE
Problems with values.csv

### ISSUE THREAD

**Issue by CMUgarte** [cldf-datasets/gata#9]
@LinguList, I made some modifications on the dataset but still run with three problems:

1. It seems that the link with parameters.csv is not working because values.csv doesn't show this column. The same happens with languages.csv.
2. There is a problem with the Source column (I get cells with something like this as an output: a;r;a;p;a;h;o;1;9;6;3). I don't know why this occurs.
3. I tried deleting the Code_ID column. Everytime I run `cldfbench makecldf`, however, it appears again.

**Comment by LinguList** [comment]
1. This is the problem of your actual raw_data file, which should not have `Parameter` as column name, but obviously `Parameter_ID`, right? I mean, we read the data in as a dictionary, then we add the dict with keywords, so if there is now key=Parameter_ID, what can we add?

**Comment by LinguList** [comment]
2. You must modify the field content then.

```python
        for row in self.etc_dir.read_csv(
            'languages.csv',
            dicts=True,
            ):
            row["Source"] = [row["Source"]]
            args.writer.objects['LanguageTable'].append(row)
```

**Comment by LinguList** [comment]
3. what do you mean by "tried"?

**Comment by CMUgarte** [comment]
> 

1. Ok, I've already changed it in gata_raw.csv as it should have been. All is working fine now. My question is (and maybe it has the same answer as point 3): why I cannot modify it on the script instead of changing it on the data.csv?

**Comment by CMUgarte** [comment]
2. Great. It now works!
3. I delete it from StructureDataset_metadata.json but it appears again when I run CLDF conversion.

**Comment by LinguList** [comment]
Yes, since it is a required field that should be addressed. In fact, you should add codes to your datasets (I propose to make a new issue for that!). Similar to "Parameter_ID" in the ValueTable, you cannot just ignore this part. It is part of the structure, you can see when checking other cldf datasets here.

**Comment by LinguList** [comment]
You can of course modify and tweak things in your script, but what I showed you is the easiest way. If you want to modify things on the fly, you should create a dictionary with the keys you desire, and then pass this to the respective table, appending it there. But it'll be more code with the settings you have here, why go for more code?

**Comment by CMUgarte** [comment]
Ok great :) It is all clear to me now. I'm closing this issue and opening a new one regarding the codes. Thanks!
